# Pré-Processamento de Dados

Base do Kaggle: Titanic

Link: https://www.kaggle.com/competitions/titanic

In [1]:
import pandas as pd # biblioteca para manipulação e análise de dados
import numpy as np # biblioteca para manipulação matemática

In [2]:
# Ferramentas de pré-processamento do scikit-learn
from sklearn.preprocessing import LabelEncoder, StandardScaler
# LabelEncoder -> Converte categorias para números
# StandardScaler -> Normaliza os dados (mesma escala)

In [3]:
# Montar o Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
df = pd.read_csv('/content/drive/MyDrive/train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
# Remover colunas irrelevantes
df = df.drop(
    columns=[
        'PassengerId',
        'Name',
        'Ticket',
        'Cabin'
    ]
)
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [6]:
# Renomear as colunas para PT-BR
df = df.rename(
    columns={
        'Survived': 'Sobreviveu',
        'Pclass': 'Classe_Passageiro',
        'Sex': 'Sexo',
        'Age': 'Idade',
        'SibSp': 'Num_irmaos_conjuges_a_bordo',
        'Parch': 'Num_pais_filhos_a_bordo',
        'Fare': 'Tarifa',
        'Embarked': 'Porto_Embarque'
    }
)

In [7]:
df.head()

,Sobreviveu,Classe_Passageiro,Sexo,Idade,Num_irmaos_conjuges_a_bordo,Num_pais_filhos_a_bordo,Tarifa,Porto_Embarque
0,0,3,male,22.0,1,0,7.2500,S
1,1,1,female,38.0,1,0,71.2833,C
2,1,3,female,26.0,0,0,7.9250,S
3,1,1,female,35.0,1,0,53.1000,S
4,0,3,male,35.0,0,0,8.0500,S

In [8]:
# Análise de valores nulos (ausentes)
df.isnull().sum()

Sobreviveu                       0
Classe_Passageiro                0
Sexo                             0
Idade                          177
Num_irmaos_conjuges_a_bordo      0
Num_pais_filhos_a_bordo          0
Tarifa                           0
Porto_Embarque                   2
dtype: int64

In [9]:
# Tratamento dos valores ausentes

# Idade -> Média
df['Idade'] = df['Idade'].fillna(df['Idade'].mean())

In [10]:
# Porto de Embarque -> Moda (o valor que mais aparece)
df['Porto_Embarque'] = df['Porto_Embarque'].fillna(df['Porto_Embarque'].mode()[0])

In [11]:
# Converter os tipos das variáveis
df['Classe_Passageiro'] = df['Classe_Passageiro'].astype(int)
df['Sobreviveu'] = df['Sobreviveu'].astype(int)

In [12]:
# Codificação das variáveis categóricas
label_encoder = LabelEncoder()

df['Sexo'] = label_encoder.fit_transform(df['Sexo'])
df['Porto_Embarque'] = label_encoder.fit_transform(df['Porto_Embarque'])

df.head()

,Sobreviveu,Classe_Passageiro,Sexo,Idade,Num_irmaos_conjuges_a_bordo,Num_pais_filhos_a_bordo,Tarifa,Porto_Embarque
0,0,3,1,22.0,1,0,7.2500,2
1,1,1,0,38.0,1,0,71.2833,0
2,1,3,0,26.0,0,0,7.9250,2
3,1,1,0,35.0,1,0,53.1000,2
4,0,3,1,35.0,0,0,8.0500,2

# Separação entre atributos (X) e alvo (y)

--> X receber todas as colunas da nossa base
Menos a coluna "Sobreviveu"
Essas colunas são as características (features) que o modelo
utilizará para aprender os padrões

--> Y vai receber apenas a coluna "Sobreviveu"

0 = não sobreviveu

1 = sobreviveu

O algoritmo aprende com X (features) e pode prever novos casos (Y).

In [13]:
X = df.drop('Sobreviveu', axis=1)
Y = df['Sobreviveu']

print("Atributos: ")
print(X)

print("Alvo: ")
print(Y)

Atributos:
     Classe_Passageiro  Sexo      Idade  Num_irmaos_conjuges_a_bordo  \
0                    3     1  22.000000                            1
1                    1     0  38.000000                            1
2                    3     0  26.000000                            0
3                    1     0  35.000000                            1
4                    3     1  35.000000                            0
..                 ...   ...        ...                          ...
886                  2     1  27.000000                            0
887                  1     0  19.000000                            0
888                  3     0  29.699118                            1
889                  1     1  26.000000                            0
890                  3     1  32.000000                            0

     Num_pais_filhos_a_bordo   Tarifa  Porto_Embarque
0                          0   7.2500               2
1                          0  71.2833               0
2                          0   7.9250               2
3                          0  53.1000               2
4                          0   8.0500               2
..                       ...      ...             ...
886                        0  13.0000               2
887                        0  30.0000               2
888                        2  23.4500               2
889                        0  30.0000               0
890                        0   7.7500               1

[891 rows x 7 columns]
Alvo:
0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Sobreviveu, Length: 891, dtype: int64

In [14]:
# Normalização de Escala
scaler = StandardScaler()
X_normalizado = scaler.fit_transform(X)

In [15]:
X_normalizado_df = pd.DataFrame(
     X_normalizado,
     columns=X.columns
)

X_normalizado_df.head()

,Classe_Passageiro,Sexo,Idade,Num_irmaos_conjuges_a_bordo,Num_pais_filhos_a_bordo,Tarifa,Porto_Embarque
0,0.827377,0.737695,-0.592481,0.432793,-0.473674,-0.502445,0.585954
1,-1.566107,-1.355574,0.638789,0.432793,-0.473674,0.786845,-1.942303
2,0.827377,-1.355574,-0.284663,-0.474545,-0.473674,-0.488854,0.585954
3,-1.566107,-1.355574,0.407926,0.432793,-0.473674,0.420730,0.585954
4,0.827377,0.737695,0.407926,-0.474545,-0.473674,-0.486337,0.585954

# Regressão

A regressão pode ser entendida como uma técnica estatística e de aprendizado de máquinas utilizado para prever um valor numérico contínuo.

Tenta responder:
> quanto?

> quantos?

> qual será o valor?

---

Objetivo: modelar uma relação entre uma variável dependentes (alvo, label, resposta) e uma ou mais variáveis dependentes (atributos, características).

In [23]:
from sklearn.model_selection import train_test_split # Dividir os dados em treino e teste
from sklearn.linear_model import LogisticRegression # Regressão Logística
from sklearn.metrics import accuracy_score #Métrica de avaliação para o nosso modelo

# Dividir a base entre treino e teste

In [20]:
X_train, X_teste, y_train, y_teste = train_test_split(
  X_normalizado_df, Y, test_size=0.25, random_state=42
)

In [25]:
# Criar o modelo de regressão logística
modelo = LogisticRegression(max_iter = 1000)

# Treinar o nosso modelo com os dados de treino
modelo.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [26]:
# Previsão no conjuto de teste
y_pred = modelo.predict(X_teste)

print("Acurácia:", accuracy_score(y_teste, y_pred))

Acurácia: 0.8071748878923767

In [33]:
# Criar um novo passageiro para a base
novo_passageiro = pd.DataFrame({
    'Classe_Passageiro': [1], #Passageiro da 3ª classe
    'Sexo': [0], #1 (masc/femin)
    'Idade': [70],
    'Num_irmaos_conjuges_a_bordo': [0], #não viaja com irmão/cônjuge
    'Num_pais_filhos_a_bordo': [0], #não viaja com pais/filhos,
    'Tarifa': [15.0],
    'Porto_Embarque': [2]
})

In [34]:
#Normalizar os dados do novo passageiro
novo_passageiro_normalizado = scaler.transform(novo_passageiro)

In [35]:
#Predição para o novo passageiro
pred = modelo.predict(novo_passageiro_normalizado)
prob = modelo.predict_proba(novo_passageiro_normalizado)

print("\n--- Predição para o novo passageiro ---")
print("Sobreviveu? (0 = NÃO, 1 = SIM)", int(pred[0]))
print("Probabilidade de NÃO sobreviver: ", prob[0][0])
print("Probabilidade de sobreviver: ", prob[0][1])

--- Predição para o novo passageiro ---
Sobreviveu? (0 = NÃO, 1 = SIM) 1
Probabilidade de NÃO sobreviver:  0.2595962348424753
Probabilidade de sobreviver:  0.7404037651575247

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(